translate:
  link:
    uk: Сайти
    uk_single: Сайт
    en: Sites
    en_single: Site
fields:
- name: id
  type: integer
  id: true
- name: code
  type: string
  isrequire: true
- name: domain
  type: string
  isrequire: true
  isstring: true
- name: headersettingsites
  type: relation
  typeRelation: OneToMany
  objectRelation: HeaderSetting
  mappedBy: site
- name: seosettingsites
  type: relation
  typeRelation: OneToMany
  objectRelation: SeoSetting
  mappedBy: site
- name: footersettingsites
  type: relation
  typeRelation: OneToMany
  objectRelation: FooterSetting
  mappedBy: site
- name: megamenusites
  type: relation
  typeRelation: OneToMany
  objectRelation: MegaMenuSetting
  mappedBy: site
- name: recipesites
  type: relation
  typeRelation: OneToMany
  objectRelation: Recipe
  mappedBy: site
- name: popularsearchsites
  type: relation
  typeRelation: OneToMany
  objectRelation: Popularsearch
  mappedBy: site
- name: facebooksettingsites
  type: relation
  typeRelation: OneToMany
  objectRelation: FacebookSetting
  mappedBy: site
- name: emailmailboxsites
  type: relation
  typeRelation: OneToMany
  objectRelation: EmailMailbox
  mappedBy: site

