#!/usr/bin/env bash
php bin/console app:export:csv RecipeTranslation
php bin/console app:export:csv Recipe
php bin/console app:export:csv RecipeCategory
php bin/console app:export:csv RecipeStep
php bin/console app:export:csv Ingredient
php bin/console app:export:csv GroupComponent
php bin/console app:export:csv Component
php bin/console app:export:csv Unit
php bin/console app:export:csv Site
php bin/console app:export:csv Locale
php bin/console app:export:csv HeaderSetting
php bin/console app:export:csv HeaderTranslation
php bin/console app:export:csv SeoSetting
php bin/console app:export:csv SeoSettingsTranslation
php bin/console app:export:csv FooterSetting
php bin/console app:export:csv FooterTranslation
php bin/console app:export:csv MegaMenuSetting
php bin/console app:export:csv MegaMenuTranslation
php bin/console app:export:csv MegaMenuType
php bin/console app:export:csv Popularsearch
php bin/console app:export:csv User