#!/usr/bin/env bash
#because User is base entity
php bin/console app:import:csv User scalar
php bin/console app:import:csv Component scalar
php bin/console app:import:csv FacebookSetting scalar
php bin/console app:import:csv GroupComponent scalar
php bin/console app:import:csv Ingredient scalar
php bin/console app:import:csv Product scalar
php bin/console app:import:csv Recipe scalar
php bin/console app:import:csv RecipeCategory scalar
php bin/console app:import:csv RecipeStep scalar
php bin/console app:import:csv RecipeTranslation scalar
php bin/console app:import:csv Unit scalar
php bin/console app:import:csv FooterSetting scalar
php bin/console app:import:csv FooterTranslation scalar
php bin/console app:import:csv HeaderSetting scalar
php bin/console app:import:csv HeaderTranslation scalar
php bin/console app:import:csv Locale scalar
php bin/console app:import:csv MegaMenuSetting scalar
php bin/console app:import:csv MegaMenuTranslation scalar
php bin/console app:import:csv MegaMenuType scalar
php bin/console app:import:csv Popularsearch scalar
php bin/console app:import:csv SeoSetting scalar
php bin/console app:import:csv SeoSettingsTranslation scalar
php bin/console app:import:csv Site scalar
php bin/console app:import:csv EmailFilter scalar
php bin/console app:import:csv EmailFilterGroup scalar
php bin/console app:import:csv EmailMailbox scalar
php bin/console app:import:csv EmailMailboxFolder scalar
php bin/console app:import:csv EmailMessage scalar
php bin/console app:import:csv HolidayTable scalar
php bin/console app:import:csv HolidayTableRecipe scalar
php bin/console app:import:csv Component association
php bin/console app:import:csv FacebookSetting association
php bin/console app:import:csv GroupComponent association
php bin/console app:import:csv Ingredient association
php bin/console app:import:csv Product association
php bin/console app:import:csv Recipe association
php bin/console app:import:csv RecipeCategory association
php bin/console app:import:csv RecipeStep association
php bin/console app:import:csv RecipeTranslation association
php bin/console app:import:csv Unit association
php bin/console app:import:csv FooterSetting association
php bin/console app:import:csv FooterTranslation association
php bin/console app:import:csv HeaderSetting association
php bin/console app:import:csv HeaderTranslation association
php bin/console app:import:csv Locale association
php bin/console app:import:csv MegaMenuSetting association
php bin/console app:import:csv MegaMenuTranslation association
php bin/console app:import:csv MegaMenuType association
php bin/console app:import:csv Popularsearch association
php bin/console app:import:csv SeoSetting association
php bin/console app:import:csv SeoSettingsTranslation association
php bin/console app:import:csv Site association
php bin/console app:import:csv EmailFilter association
php bin/console app:import:csv EmailFilterGroup association
php bin/console app:import:csv EmailMailbox association
php bin/console app:import:csv EmailMailboxFolder association
php bin/console app:import:csv EmailMessage association
php bin/console app:import:csv HolidayTable association
php bin/console app:import:csv HolidayTableRecipe association